--liquibase formatted sql
--changeset andre.bongiolo:1
CREATE TABLE PIZZAS (
ID          BIGINT PRIMARY KEY,
DESCRICAO VARCHAR(255),
CODIGO VARCHAR(20),
BORDA VARCHAR(10),
PRECO FLOAT,
QUANTIDADE_SABORES BIGINT,
QUANTIDADE_FATIAS BIGINT
);
--rollback DROP PIZZAS

--changeset andre.bongiolo:2
COMMENT ON TABLE PIZZAS IS 'Pizzas';
COMMENT ON COLUMN PIZZAS.ID IS 'Identificador da pizza';
COMMENT ON COLUMN PIZZAS.DESCRICAO IS 'Descrição';
COMMENT ON COLUMN PIZZAS.CODIGO IS 'Código';
COMMENT ON COLUMN PIZZAS.BORDA IS 'Indica se tem borda';
COMMENT ON COLUMN PIZZAS.PRECO IS 'Preço';
COMMENT ON COLUMN PIZZAS.QUANTIDADE_FATIAS IS 'Quantidade';
COMMENT ON COLUMN PIZZAS.QUANTIDADE_SABORES IS 'Quantidade';
--rollback not required

--changeset andre.bongiolo:3
CREATE SEQUENCE SEQ_PIZZAS;
--rollback DROP SEQ_PIZZAS
