--liquibase formatted sql
--changeset andre.bongiolo:1
INSERT INTO public.PIZZAS( ID, DESCRICAO,BORDA, PRECO,QUANTIDADE_SABORES,QUANTIDADE_FATIAS)
  VALUES ((SELECT NEXTVAL('SEQ_PIZZAS')),'Pizza broto',false,19.90,1,4);

INSERT INTO public.PIZZAS( ID, DESCRICAO,BORDA, PRECO,QUANTIDADE_SABORES,QUANTIDADE_FATIAS)
  VALUES ((SELECT NEXTVAL('SEQ_PIZZAS')),'Pizza pequena',true,27.90,2,6);

INSERT INTO public.PIZZAS( ID, DESCRICAO,BORDA, PRECO,QUANTIDADE_SABORES,QUANTIDADE_FATIAS)
  VALUES ((SELECT NEXTVAL('SEQ_PIZZAS')),'Pizza Média',true,36.00,2,8);

INSERT INTO public.PIZZAS( ID, DESCRICAO,BORDA, PRECO,QUANTIDADE_SABORES,QUANTIDADE_FATIAS)
  VALUES ((SELECT NEXTVAL('SEQ_PIZZAS')),'Pizza Grande',true,46.00,3,12);

INSERT INTO public.PIZZAS( ID, DESCRICAO,BORDA, PRECO,QUANTIDADE_SABORES,QUANTIDADE_FATIAS)
  VALUES ((SELECT NEXTVAL('SEQ_PIZZAS')),'Pizza Gigante',true,53.90,4,16);

--rollback not required

